[features]
seeds = false
skip-lint = false

[programs.devnet]
hgnft = "4WTUyXNcf6QCEj76b3aRDLPewkPGkXFZkkyf3A3vua1z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/hssn-demo2-1.ts"
test2 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/hssn-demo2-2.ts"
test3 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/hssn-demo2-3.ts"