[features]
seeds = false
skip-lint = false

[programs.devnet]
game = "7vULRbi3voKqainRSAFRZhqPDUvPi9NzedaW59VMevPM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://native-rpc.sonic.game"
wallet = "/Users/havencross/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
